trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.18
    endpoint: GitHub (SFA)
  
stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml