jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
  variables:
  - group: Prod Management Resources
  - name: buildConfiguration
    value: release
  - group: Prod Management Resources
  - name: buildPlatform
    value: anycpu
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'src/**/*.csproj'
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
      
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.UnitTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  - task: DotNetCoreCLI@2
    displayName: AcceptanceTest
    inputs:
      command: test
      projects: '**/*.AcceptanceTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Function App Apprentice Commitments Jobs'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.ApprenticeCommitments.Jobs.Functions/SFA.DAS.ApprenticeCommitments.Jobs.Functions.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'